const MESSAGE_MAX_LENGTH = 2000;
const MESSAGE_EDIT_TIME_LIMIT = 24; // hours
const USERNAME_MIN_LENGTH = 3;
const USERNAME_MAX_LENGTH = 30;
const PASSWORD_MIN_LENGTH = 6;
const CHANNEL_NAME_MAX_LENGTH = 100;
const SERVER_NAME_MAX_LENGTH = 100;

const CHANNEL_TYPES = {
  TEXT: 'text',
  VOICE: 'voice'
};

module.exports = {
  MESSAGE_MAX_LENGTH,
  MESSAGE_EDIT_TIME_LIMIT,
  USERNAME_MIN_LENGTH,
  USERNAME_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  CHANNEL_NAME_MAX_LENGTH,
  SERVER_NAME_MAX_LENGTH,
  CHANNEL_TYPES
};

