declare const styles: {
  readonly "button": string;
  readonly "conflictIcon": string;
  readonly "conflictMessage": string;
  readonly "conflictMessages": string;
  readonly "conflictRow": string;
  readonly "defaultLabel": string;
  readonly "defaultRow": string;
  readonly "defaultValue": string;
  readonly "disabled": string;
  readonly "editIconLeft": string;
  readonly "hasValue": string;
  readonly "input": string;
  readonly "inputWrapper": string;
  readonly "layout": string;
  readonly "popout": string;
  readonly "popoutActions": string;
  readonly "popoutActionsLeft": string;
  readonly "popoutHeader": string;
  readonly "popoutHint": string;
  readonly "popoutTitle": string;
  readonly "pulse": string;
  readonly "recorder": string;
  readonly "recorderBox": string;
  readonly "recorderBoxRecording": string;
  readonly "recorderIcon": string;
  readonly "recorderText": string;
};
export = styles;

