declare const styles: {
  readonly "alignmentControlsRow": string;
  readonly "alignmentLabel": string;
  readonly "alignmentSection": string;
  readonly "brandingContent": string;
  readonly "cardAlignmentControls": string;
  readonly "container": string;
  readonly "errorMessage": string;
  readonly "iconField": string;
  readonly "iconPreview": string;
  readonly "iconUploadActions": string;
  readonly "iconUploadButtons": string;
  readonly "iconUploadContainer": string;
  readonly "iconUploadDescription": string;
  readonly "imagePreviewColumn": string;
  readonly "imagePreviewContainer": string;
  readonly "imageUploadActions": string;
  readonly "imageUploadButtons": string;
  readonly "imageUploadDescription": string;
  readonly "invitePageButton": string;
  readonly "notificationOptions": string;
  readonly "previewButtonContainer": string;
  readonly "previewButtonDescription": string;
  readonly "previewButtonRow": string;
  readonly "section": string;
  readonly "sectionDescription": string;
  readonly "sectionHeader": string;
  readonly "sectionTitle": string;
  readonly "settingsContent": string;
  readonly "splashSettingsButtons": string;
  readonly "splashSettingsColumn": string;
  readonly "splashSettingsColumnRight": string;
  readonly "splashSettingsContainer": string;
  readonly "splashSettingsHelper": string;
  readonly "splashSettingsRow": string;
};
export = styles;

