declare const styles: {
  readonly "loadingContainer": string;
  readonly "modalContent": string;
  readonly "modalLayout": string;
  readonly "modalRoot": string;
  readonly "noReactionsContainer": string;
  readonly "noReactionsText": string;
  readonly "reactionCount": string;
  readonly "reactionEmoji": string;
  readonly "reactionFilterButton": string;
  readonly "reactionFilterButtonContainer": string;
  readonly "reactionFilterButtonIdle": string;
  readonly "reactionFilterButtonSelected": string;
  readonly "reactionFiltersPane": string;
  readonly "reactionListContainer": string;
  readonly "reactionListPanel": string;
  readonly "reactorInfo": string;
  readonly "reactorItem": string;
  readonly "reactorItemBorder": string;
  readonly "reactorName": string;
  readonly "reactorScroller": string;
  readonly "reactorTag": string;
  readonly "removeReactionButton": string;
  readonly "removeReactionIcon": string;
  readonly "scrollerColumn": string;
  readonly "scrollerPadding": string;
  readonly "sidebar": string;
  readonly "sidebarScroller": string;
  readonly "srOnly": string;
};
export = styles;

