declare const styles: {
  readonly "backdropSlot": string;
  readonly "centeredOnMobile": string;
  readonly "content": string;
  readonly "contentNoPadding": string;
  readonly "dark": string;
  readonly "focusLock": string;
  readonly "footer": string;
  readonly "fullscreen": string;
  readonly "header": string;
  readonly "headerInner": string;
  readonly "headerText": string;
  readonly "insetCloseButton": string;
  readonly "insetCloseButtonContainer": string;
  readonly "large": string;
  readonly "layer": string;
  readonly "layerCentered": string;
  readonly "layerFullscreen": string;
  readonly "layerFullscreenMobile": string;
  readonly "layout": string;
  readonly "light": string;
  readonly "medium": string;
  readonly "mobileSlideIn": string;
  readonly "mobileSlideOut": string;
  readonly "modalBackdrop": string;
  readonly "root": string;
  readonly "screenReaderLabel": string;
  readonly "slideInFromRight": string;
  readonly "slideOutToRight": string;
  readonly "small": string;
  readonly "surface": string;
  readonly "xlarge": string;
};
export = styles;

