declare const styles: {
  readonly "callBanner": string;
  readonly "callBannerMobile": string;
  readonly "callBannerMobileLabel": string;
  readonly "callControls": string;
  readonly "callControlsMobile": string;
  readonly "callParticipant": string;
  readonly "callParticipantAvatar": string;
  readonly "callParticipantPulse": string;
  readonly "callParticipantRinging": string;
  readonly "callParticipantRipple": string;
  readonly "callParticipantRipple0": string;
  readonly "callParticipantRipple1": string;
  readonly "callParticipantRipple2": string;
  readonly "callParticipantsRow": string;
  readonly "callSheetContent": string;
  readonly "callSheetControls": string;
  readonly "callSheetStatus": string;
  readonly "channelContainer": string;
  readonly "channelLayout": string;
  readonly "compactVoiceCallView": string;
  readonly "emptyState": string;
  readonly "emptyStateDescription": string;
  readonly "emptyStateIcon": string;
  readonly "emptyStateTitle": string;
  readonly "minimizeButton": string;
  readonly "minimizeButtonIcon": string;
  readonly "voiceCallContainer": string;
};
export = styles;

